# Generated by Django 4.1 on 2022-09-03 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LibM', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='retal_period',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
